### ISSUE TITLE
How to write an app for the sphere?

### ISSUE THREAD

**Issue by miguelaferreira** [ninjasphere/ninjasphere#36]
I'm very excited with my sphere, but I have to say, it doesn't do much yet.
So I'm keen to start making something for it. I want basic things like:
- orchestration: send a command to a device, wait for a few seconds and send another command to a different device 
- reaction: monitor a device power consumption, and based on thresholding, send commands to other devices.

The best thing to have would be a tutorial, but if that is not possible, then an example app would be a great start.

**Comment by elliots** [comment]
Hi Miguela, 

There isn't enough in the way of documentation yet (we'll get there), but I've opened up the code for the led controller, which should help get you started talking to HomeCloud (to search for things to control) and how to actuate the devices you find. Once we have the control aspects on Sphere done (LED and phone apps) we'll be starting work on apps and the rules engine in ernest.

Of course, because everything is done via JSON-RPC over MQTT, you can see everything that happens on the sphere by running `mosquitto-sub -v -t '#'`

Take a look and see how you go... happy to help when you get stuck.

https://github.com/ninjasphere/sphere-go-led-controller

**Comment by miguelaferreira** [comment]
Thanks @elliots.
